# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Sample-Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.0.0'
    pod 'RxCocoa', '6.0.0'

  target 'RxSwift-Sample-ProjectTests' do
    inherit! :search_paths
    pod 'RxBlocking', '6.0.0'
    pod 'RxTest', '6.0.0'
  
  end

  target 'RxSwift-Sample-ProjectUITests' do
    # Pods for testing
  end

end
